import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import the Inter font
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Navbar from "@/components/Navbar";

// Load the Inter font from Google
const inter = Inter({
  subsets: ["latin"], // Specify subsets if needed
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
